package config

// all env variables are managed centrally
const (
	// for http
	_HTTP_ADDRESS                     = "HTTP_ADDRESS"
	_HTTP_READ_TIMEOUT_SECONDS        = "HTTP_READ_TIMEOUT_SECONDS"
	_HTTP_READ_HEADER_TIMEOUT_SECONDS = "HTTP_READ_HEADER_TIMEOUT_SECONDS"
	_HTTP_WRITE_TIMEOUT_SECONDS       = "HTTP_WRITE_TIMEOUT_SECONDS"
	_HTTP_IDLE_TIMEOUT_SECONDS        = "HTTP_IDLE_TIMEOUT_SECONDS"
)
