name: ci_test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go 1.17.13
      uses: actions/setup-go@v3
      with:
        go-version: 1.17.13

    - name: Test
      run: go test -v ./...
